services:
  - type: web
    name: nutri-champ-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    plan: free
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: MY_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false